#! /bin/bash

PACKAGE_INSTALLATION_ROOT=~/packages
PACKAGE_NAME=boost
PACKAGE_VERSION=1.55.0

mkdir -p $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION

cd boost_1_55_0
./bootstrap.sh --prefix=$PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION
./bjam cxxflags=-fPIC --disable-icu -a install
cd ..
cp package.py $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION

